exports.states = [
  {statefp : "01", name : "Alabama"},
  {statefp : "02", name : "Alaska"},
  {statefp : "04", name : "Arizona"},
  {statefp : "05", name : "Arkansas"},
  {statefp : "06", name : "California"},
  {statefp : "08", name : "Colorado"},
  {statefp : "09", name : "Connecticut"},
  {statefp : "10", name : "Delaware"},
  {statefp : "11", name : "District of Columbia"},
  {statefp : "12", name : "Florida"},
  {statefp : "13", name : "Georgia"},
  {statefp : "15", name : "Hawaii"},
  {statefp : "16", name : "Idaho"},
  {statefp : "17", name : "Illinois"},
  {statefp : "18", name : "Indiana"},
  {statefp : "19", name : "Iowa"},
  {statefp : "20", name : "Kansas"},
  {statefp : "21", name : "Kentucky"},
  {statefp : "22", name : "Louisiana"},
  {statefp : "23", name : "Maine"},
  {statefp : "24", name : "Maryland"},
  {statefp : "25", name : "Massachusetts"},
  {statefp : "26", name : "Michigan"},
  {statefp : "27", name : "Minnesota"},
  {statefp : "28", name : "Mississippi"},
  {statefp : "29", name : "Missouri"},
  {statefp : "30", name : "Montana"},
  {statefp : "31", name : "Nebraska"},
  {statefp : "32", name : "Nevada"},
  {statefp : "33", name : "New Hampshire"},
  {statefp : "34", name : "New Jersey"},
  {statefp : "35", name : "New Mexico"},
  {statefp : "36", name : "New York"},
  {statefp : "37", name : "North Carolina"},
  {statefp : "38", name : "North Dakota"},
  {statefp : "39", name : "Ohio"},
  {statefp : "40", name : "Oklahoma"},
  {statefp : "41", name : "Oregon"},
  {statefp : "42", name : "Pennsylvania"},
  {statefp : "44", name : "Rhode Island"},
  {statefp : "45", name : "South Carolina"},
  {statefp : "46", name : "South Dakota"},
  {statefp : "47", name : "Tennessee"},
  {statefp : "48", name : "Texas"},
  {statefp : "49", name : "Utah"},
  {statefp : "50", name : "Vermont"},
  {statefp : "51", name : "Virginia"},
  {statefp : "53", name : "Washington"},
  {statefp : "54", name : "West Virginia"},
  {statefp : "55", name : "Wisconsin"},
  {statefp : "56", name : "Wyoming"},
  {statefp : "72", name : "Puerto Rico"}
]